# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
events = Event.create([
                          { name: 'Apple’s Big iPhone Event', description: 'The launch comes at an important time for Apple, which continues to make a lot of money from the iPhone but has seen its global market share dip amid a growing wave of lower-cost Android devices, as well as an intense battle with archrival Samsung. One of the key questions is whether Apple adopts a new tactic to address the midrange of the smartphone market. Historically, Apple has gone after those customers by offering its year-old and two-year-old models for $100 and $200 less than a new iPhone. However, there has been a great deal of talk that the company will debut a new lower-cost iPhone alongside whatever update it has in store for the current iPhone 5. Much of the speculation there has centered on the usual kinds of camera and processor enhancements, as well as the likelihood of a fingerprint sensor. That has been expected ever since Apple acquired Authentec last year.'},
                          { name: 'The cloud grows up', description: 'Hundreds of startups and small businesses have launched and scaled in the last few years, with little more than a bright idea and a credit card – all thanks to affordable cloud solutions like Amazon, Box, and Salesforce. The cloud continues to deliver these advantages today. But now it’s not just a promise: Cloud technologies have a credible story and solid case studies to tell prospective customers in the enterprise. Now in its third year, VentureBeat’s highly-acclaimed CloudBeat conference will track the growing maturity of the cloud through two days of high-value discussions, case studies, breakout sessions, and exclusive announcements. Unlike nearly all other cloud events, the customers themselves are front and center. Their discussions with vendors and other experts unearth rare lessons on cloud adoption, providing insights and actionable data on new technologies, what really works, who’s buying what, and where the industry is going. In other words, it’s not just your usual empty promises. CloudBeat will be filled with data and insights from the real world.' },
                          { name: 'TechCrunch Disrupt', description: 'TechCrunch Disrupt is one of the most anticipated technology conferences of the year. This September 7-11, TechCrunch will be bringing Disrupt back to San Francisco to reveal an all new slate of outstanding startups, influential speakers, guests and more to the stage. If you’d like a quick overview, check out the video below. The Hackathon kicks everything off, followed by our main event, which starts every morning with panels of special speakers and guests, one-on-one chats featuring TechCrunch writers and editors, special guest speakers and judges, leading venture capitalists and fascinating entrepreneurs addressing the most important topics facing today’s tech landscape. In the afternoons, the Startup Battlefield presentations begin, with the final presentations held on the last day of Disrupt. Please note: we will publish our agenda featuring panels, speakers, special guests and judges as we get closer to the event.' },
                          { name: 'GamesCom', description: 'Partnership with Indie MEGABOOTH starts this year with a booth in the business area, where Indie Developers can get information and integration. At gamescom 2014, an Indie MEGABOOTH in entertainment area is planned. After the success of the Indie MEGABOOTH group exhibits in the U.S. in the last two years, Overlord Kelly Wallick has been in talks with gamescom executives to bring the initiative to Europe. In 2013, Koelnmesse and Indie MEGABOOTH offer Indie Game Developers a contact platform in the business area (Hall 4.2, Booth D-027), where they can get information about participation in the MEGABOOTH Project at gamescom for 2014. Next year the organizers want to realize a MEGABOOTH area in the entertainment area.' },
                          { name: 'GeekWire Summit Thursday, September 12th 9:30 a.m. – 5:30 p.m. Sheraton Seattle, Downtown Seattle', description: 'Where can you hear from a top Silicon Valley venture capitalist, the leader of Microsoft’s Halo business, HBO’s top technology executive, the former Nordstrom.com president, a visionary photographer who’s making his mark in online education, and an Amazon veteran aiming to upend traditional retail with the help of robots? It’s the GeekWire Summit, our biggest event of the year, coming up on Sept. 12 in downtown Seattle. And that’s just part of what we have in store. The GeekWire Summit is the premier technology conference in the Pacific Northwest. Organized and curated by GeekWire’s John Cook and Todd Bishop, this event brings together engineers, entrepreneurs and business leaders from around the region and the country for conversations and insights at the intersection of business and technology, reflecting GeekWire’s mission to inform, empower and unite the region’s technology community. Tickets are available here. Continue reading below for highlights from the agenda for this one-of-a-kind conference.' }
                      ])
events.each do |event|
  Guest.create(name: 'Ronen', email: 'ronen@gmail.com', phone: '6473456543', designation: 'Mr', event_id: event.id)
  Guest.create(name: 'Marlina', email: 'marlina@gmail.com', phone: '5387454356', designation: 'Ms', event_id: event.id)
  Guest.create(name: 'Bohdan', email: 'bohdan@gmail.com', phone: '3672453275', designation: 'Mr', event_id: event.id)
end